apiVersion: v1
kind: Service
metadata:
  name: databases
  labels:
    app: databases
spec:
  ports:
    - port: 3306
  selector:
    app: databases
    tier: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: databases
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: databases
  labels:
    app: databases
spec:
  selector:
    matchLabels:
      app: databases
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: databases
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql-databases
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql-databases
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim