apiVersion: apps/v1
kind: Deployment

metadata:
    name: accommodation-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: accommodation
    template:
        metadata:
            labels:
                app: accommodation
        spec:
            containers:
                - name: accommodation-container
                  image: inno2173/accommodation:latest
---
apiVersion: v1
kind: Service
metadata: 
    name: accommodations-srv

spec:
    selector: 
        app: accommodation
    ports:
        - name: accommodation
          protocol: TCP
          port: 4001 
          targetPort: 4001

---
    apiVersion: v1
    kind: Service
    metadata:
        name: accommodations-service
    spec: 
        type: NodePort
        selector:
            app: accommodation
        ports:
            - name: accommodations
              port: 4001
              targetPort: 4001    

