apiVersion: apps/v1
kind: Deployment

metadata:
    name: apigateway-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: apigateway
    template:
        metadata:
            labels:
                app: apigateway
        spec:
            containers:
                - name: apigateway
                  image: inno2173/apigateway:latest

---
apiVersion: v1
kind: Service
metadata: 
    name: apigateway-srv

spec:
    selector: 
        app: apigateway
    ports:
        - name: apigateway
          protocol: TCP
          port: 7000 
          targetPort: 7000
 
---

    apiVersion: v1
    kind: Service
    metadata:
        name: apigateway-service
    spec: 
        type: NodePort
        selector:
            app: apigateway
        ports:
            - name: apigateway
              port: 7000
              targetPort: 7000
