apiVersion: apps/v1
kind: Deployment

metadata:
    name: authentication-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: authentication
    template:
        metadata:
            labels:
                app: authentication
        spec:
            containers:
                - name: authentication-container
                  image: inno2173/authentication:latest

---
apiVersion: v1
kind: Service
metadata: 
    name: authentication-srv

spec:
    selector: 
        app: authentication
    ports:
        - name: authenticationport
          protocol: TCP
          port: 4000 
          targetPort: 4000

---
    apiVersion: v1
    kind: Service
    metadata:
        name: authentication-service
    spec: 
        type: NodePort
        selector:
            app: authentication
        ports:
            - name: authentication
              port: 4000
              targetPort: 4000    

