version: '3'
services: 
    node-authentication-microserevice:
        container_name: authentication-microservice
        restart: always
        build: .
        ports: 
            - "7009:7009"
        links:
            - "mysql-PeopleManagementDB"
    mysql-PeopleManagementDB:
        container_name: peopledb
        image: mysql:8.0.2
        environment: 
            MYSQL_ROOT_PASSWORD: password2
            MYSQL_DATABASE: PeopleManagementDB
        ports: 
            - "3302:3306"
