apiVersion: apps/v1
kind: Deployment
metadata:
    name: reviews-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: reviews
    template:
        metadata:
            labels:
                app: reviews
        spec:
            containers:
                - name: reviews-container
                  image: inno2173/reviews:latest
---
apiVersion: v1
kind: Service
metadata: 
    name: reviews-srv
spec:
    selector: 
        app: reviews
    ports:
        - name: reviews
          protocol: TCP
          port: 4002 
          targetPort: 4002
---
    apiVersion: v1
    kind: Service
    metadata:
        name: reviews-service
    spec: 
        type: NodePort
        selector:
            app: reviews 
        ports:
            - name: reviews 
              port: 4002
              targetPort: 4002